name = "MCUCommon"
uuid = "455ac959-662e-47bc-a1c5-e582af05f21d"
authors = ["Sukera <Seelengrab@users.noreply.github.com>"]
version = "0.1.5"

[deps]
FieldFlags = "3debba03-e216-4816-844a-cb4454e272d5"

[compat]
FieldFlags = "0.4"
julia = "1.10"
